apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::950421700892:role/jenkins-role
      username: jenkins
      groups:
        - system:masters
